# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui_docnix.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 171)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridGroupBox = QtWidgets.QGroupBox(Dialog)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.ln_tentativas = QtWidgets.QLineEdit(self.gridGroupBox)
        self.ln_tentativas.setStyleSheet("QLineEdit {\n"
"                border: 1px solid #3498db; /* Cor da borda */\n"
"                border-radius: 5px; /* Cantos arredondados */\n"
"                padding: 1px; /* Espaçamento interno */\n"
"                background-color: #ecf0f1; /* Cor de fundo */\n"
"                selection-background-color: #3498db; /* Cor de fundo da seleção de texto */\n"
"                color: #2c3e50; /* Cor do texto */\n"
"            }\n"
"            QLineEdit:hover {\n"
"                border: 2px solid #2980b9; /* Cor da borda ao passar o mouse */\n"
"            }")
        self.ln_tentativas.setObjectName("ln_tentativas")
        self.gridLayout.addWidget(self.ln_tentativas, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridGroupBox1 = QtWidgets.QGroupBox(self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridGroupBox1.sizePolicy().hasHeightForWidth())
        self.gridGroupBox1.setSizePolicy(sizePolicy)
        self.gridGroupBox1.setMinimumSize(QtCore.QSize(0, 40))
        self.gridGroupBox1.setStyleSheet("background-color: rgb(0, 0, 75);")
        self.gridGroupBox1.setObjectName("gridGroupBox1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridGroupBox1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gridGroupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gridGroupBox1, 0, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 2)
        self.btn_iniciar = QtWidgets.QPushButton(self.gridGroupBox)
        self.btn_iniciar.setStyleSheet("QPushButton {\n"
"                background-repeat: none;\n"
"                border: 2px solid rgb(0, 0, 127);\n"
"                color: rgb(0, 0, 127);\n"
"                padding: 5px; /* Ajuste conforme necessário */\n"
"                border-radius: 10px; /* Ajuste o valor conforme necessário */\n"
"            }\n"
"QPushButton:hover {\n"
"                background-color: rgba(0, 0, 127, 50);\n"
"            }")
        self.btn_iniciar.setObjectName("btn_iniciar")
        self.gridLayout.addWidget(self.btn_iniciar, 2, 0, 1, 2)
        self.gridLayout_3.addWidget(self.gridGroupBox, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Docnix"))
        self.label_2.setText(_translate("Dialog", "Quantidade de tentativas:"))
        self.label.setText(_translate("Dialog", "Abrir Docnix"))
        self.label_3.setText(_translate("Dialog", "*Para encerrar durante o uso clique com botão direito do mouse"))
        self.btn_iniciar.setText(_translate("Dialog", "Iniciar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
